# Generated by Django 6.0.6 on 2026-07-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pickup_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='picked_up_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
