# Generated by Django 6.0.6 on 2026-07-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pickup_picked_up_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
