# Generated by Django 6.0.6 on 2026-07-29 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_pickup_delivered_at_alter_pickup_picked_up_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pickup',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickup',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('cash', 'Cash')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_category', models.CharField(choices=[('d', 'Drycleaning'), ('i', 'Ironing')], default='d', max_length=1)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name', 'item_category'],
                'unique_together': {('name', 'item_category')},
            },
        ),
        migrations.CreateModel(
            name='PickupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_items', to='myapp.item')),
                ('pickup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.pickup')),
            ],
        ),
    ]
