# Generated by Django 6.0.6 on 2026-07-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_pickup_amount_paid_pickup_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
