# Generated by Django 6.0.6 on 2026-08-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_historicaladvance_historicalattendance_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pickupitem',
            constraint=models.UniqueConstraint(fields=('pickup', 'item'), name='unique_pickup_item'),
        ),
    ]
