# Generated by Django 6.0.6 on 2026-08-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_expense_historicalexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
