# Generated by Django 6.0.6 on 2026-09-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_historicallocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpickup',
            name='invoice_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pickup',
            name='invoice_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
