# Generated by Django 6.0.6 on 2026-09-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_historicalpickup_invoice_id_pickup_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpickup',
            name='item_category',
            field=models.CharField(blank=True, choices=[('d', 'Drycleaning'), ('i', 'Ironing'), ('l', 'Laundry'), ('c', 'Chemical Wash')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pickup',
            name='item_category',
            field=models.CharField(blank=True, choices=[('d', 'Drycleaning'), ('i', 'Ironing'), ('l', 'Laundry'), ('c', 'Chemical Wash')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='item_category',
            field=models.CharField(choices=[('d', 'Drycleaning'), ('i', 'Ironing'), ('l', 'Laundry'), ('c', 'Chemical Wash')], default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('d', 'Drycleaning'), ('i', 'Ironing'), ('l', 'Laundry'), ('c', 'Chemical Wash')], default='d', max_length=1),
        ),
    ]
