# Generated by Django 6.0.6 on 2026-09-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_historicalpickup_item_category_pickup_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpickup',
            name='finished_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='myapp.employee'),
        ),
        migrations.AddField(
            model_name='pickup',
            name='finished_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_pickups', to='myapp.employee'),
        ),
        migrations.AlterField(
            model_name='historicalpickup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('processing', 'Processing'), ('finished', 'Finished'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('processing', 'Processing'), ('finished', 'Finished'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
